consultation:
  text: >
    ###### **Initial Consultation**

    Have no idea where to start? Email us at bigriverwebdesign@gmail.com to set up a free phone consultation. We can work with you to strategize about what a website can do for your organization and figure out what tools are appropriate to use.
design:
  text: >
    ###### **Theme Design and Development**

    Looking for something quick and simple? We use prebuilt WordPress, Nationbuilder and Squarespace themes that look great right out of the box.
    <br><br>
    Looking for something customized? We work with professional designers to create a site with an elegant and unique visual style, then turn it over to the coders to make the vision a reality.
content:
  text: >
    ###### **Content Generation**

    Need content for your site? We work with professional photographers, videographers, writers, and editors so that you don't have to worry about it.
hosting:
  text: >
    ###### **Website Hosting and Maintenance**

    Our website hosting package means that you don't have to worry about dealing with another hosting company because we take care of it for you. Our WordPress maintenance package keeps sites updated, backed up, and checks them for malware on a regular basis. For more information, contact us at bigriverwebdesign@gmail.com.
